//===- Interfaces.td ---------------------------------------*- tablegen -*-===//
//
// This is the convenience include for all Bit dialect interfaces.
//
//===----------------------------------------------------------------------===//

#ifndef BIT_INTERFACES
#define BIT_INTERFACES

include "base2-mlir/Dialect/Bit/Interfaces/BitSequenceAttr.td"
include "base2-mlir/Dialect/Bit/Interfaces/BitSequenceType.td"
include "base2-mlir/Dialect/Bit/Interfaces/LogicOp.td"

#endif
