/// Doctest driver main entry point.
///
/// @file
/// @author     Karl F. A. Friebel (karl.friebel@tu-dresden.de)

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

// DO NOT EDIT THIS FILE
